# Wrangler configuration for Cloudflare Pages
name = "noarousal"
pages_build_output_dir = "dist"
compatibility_date = "2026-06-27"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "noarousal_db"
database_id = "e2ffd5d9-bd33-4b49-bff1-4d19ab13a5b8"
